// <auto-generated />
using System;
using HRA.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRA.EF.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20211125031449_update_coltype")]
    partial class update_coltype
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HRA.EF.Horse", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Father")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mother")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherFather")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherMother")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginRanch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Horses");
                });

            modelBuilder.Entity("HRA.EF.Race", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AgeCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baba")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<string>("FurlongTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ground")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("No")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfHorse")
                        .HasColumnType("int");

                    b.Property<string>("Pattern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rotate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<string>("Rule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Up3F")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Up4F")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WeightRule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wether")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("HRA.EF.RaceCard", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("Blinkers")
                        .HasColumnType("bit");

                    b.Property<decimal>("BurdenWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Favorite")
                        .HasColumnType("int");

                    b.Property<decimal>("Fluctuation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GateNo")
                        .HasColumnType("int");

                    b.Property<decimal>("HorseWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Jokey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Last3F")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Margin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("No")
                        .HasColumnType("int");

                    b.Property<string>("RaceID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaceRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Time")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Trainer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("RaceCards");
                });
#pragma warning restore 612, 618
        }
    }
}
